name: workoutv2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.8
  sqflite_common_ffi: ^2.2.0
  sqflite_common_ffi_web: ^0.4.5+4
  path: ^1.8.3
  path_provider: ^2.0.14
  shared_preferences: ^2.5.3
  provider: ^6.1.3
  table_calendar: ^3.0.9
  fl_chart: ^0.71.0
  intl: ^0.19.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    #- assets/images/workout_db_test.db
    - assets/images/wireGuySVG.svg
    - assets/images/wireGuySVG_Abs.svg
    - assets/images/wireGuySVG_Arms.svg
    - assets/images/wireGuySVG_Chest.svg
    - assets/images/wireGuySVG_Legs.svg
#- assets/my_workout_database.db
