name: workoutv2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.8
  sqflite_common_ffi: ^2.2.0
  sqflite_common_ffi_web: ^0.4.5+4
  path: ^1.8.3
  path_provider: ^2.0.14
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  #generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/workout_db_test.db
#- assets/my_workout_database.db
